version: "3.8"

networks:
  app-scspaceships_net:
    name: wiremock_network
    driver: bridge
  app-wiremock_net:
    name: wiremock_net
    driver: bridge
  database_net: 
    name: database_net
    driver: bridge

volumes: 
  scspaceships-data:    

services:
  app-wiremock:    
    container_name: app-wiremock
    build:
      context: "./wiremock"
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - app-wiremock_net
    volumes:
      - scspaceships-data:/data
  app-frontend: 
    container_name: app-frontend
    build: 
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-scspaceships_net  
    volumes:
      - scspaceships-data:/data
